title: Fawry SoftPOS Web SDK Docs
description: Integration guide for Fawry SoftPOS Web Payment SDK
baseurl: "/fawry-soft-pos-web-sdk-docs"
url: "https://fawry-tech.github.io"

theme: just-the-docs

color_scheme: light

search_enabled: true

heading_anchors: true

back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  "View on GitHub":
    - "https://github.com/eslamwael74/fawry-soft-pos-web-sdk"

footer_content: "&copy; Fawry Payment Solutions. All rights reserved."

nav_sort: case_insensitive

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

exclude:
  - node_modules/
  - vendor/
  - Gemfile.lock
